mongo:
  options:
    #控制系统在发生连接错误时是否重试 ，默以为false --boolean
    autoConnectRetry: false
    #在建立（打开）套接字连接时的超时时间（ms），默以为0（无穷） --int
    connectTimeout: 100
    #每个主机答应的连接数（每个主机的连接池大小），当连接池被用光时，会被阻塞住 ，默以为10 --int
    connectionsPerHost: 10
    #被阻塞线程从连接池获取连接的最长等待时间（ms） --int
    maxWaitTime: 1000
    #套接字超时时间;该值会被传递给Socket.setSoTimeout(int)。默以为0（无穷） --int
    socketTimeout: 100
    #multiplier for connectionsPerHost for # of threads that can block if connectionsPerHost is 10, and threadsAllowedToBlockForConnectionMultiplier is 5, then 50 threads can block more than that and an exception will be throw --int
    threadsAllowedToBlockForConnectionMultiplier: 5
server:
  selection:
    timeout: 100
